In [216]:
!make

gcc -MM main.c > deps.make
gcc -g   -c -o main.o main.c
gcc -g -Xlinker -rpath='$ORIGIN/' -o  solver main.o gauss.so -lm


In [1]:
import numpy as np

# Tests

## 4 Default tests

### Test 1

In [218]:
A = np.array([
    [4, -3, 1, 5],
    [1, -2, -2, -3],
    [3, -1, 2, 0],
    [2, 3, 2, -8]
])
b = np.array([7, 3, -1, -7])
for x in np.linalg.solve(A, b):
    print("%lf" % x, end='\n')
print("Det", end=' ')
print(np.linalg.det(A))
print("A^-1", end='\n')
print(np.linalg.inv(A))
print("Condit", end=' ')
print(np.linalg.norm(A)*np.linalg.norm(np.linalg.inv(A)))

2.000000
1.000000
-3.000000
1.000000
Det 134.99999999999991
A^-1
[[ 0.53333333  0.         -0.6         0.33333333]
 [ 0.51851852 -0.22222222 -0.88888889  0.40740741]
 [-0.54074074 -0.11111111  0.95555556 -0.2962963 ]
 [ 0.19259259 -0.11111111 -0.24444444  0.03703704]]
Condit 23.773069800440698


#### Метод Гаусса

In [221]:
!./solver < input

Use default problems?(0-3 yes; 4 - specific): 
Types:
1 - relaxation method
0 - simple methods
Which type? Use algorithm with leading element?(1/0) 
---------SIMPLE_GAUSS_METHOD SOLUTION---------
Linear system is is:
	x1*4.00 - x2*3.00 + x3*1.00 + x4*5.00 = 7.00
	x1*1.00 - x2*2.00 - x3*2.00 - x4*3.00 = 3.00
	x1*3.00 - x2*1.00 + x3*2.00 + x4*-0.00 = -1.00
	x1*2.00 + x2*3.00 + x3*2.00 - x4*8.00 = -7.00
A matrix is:
	4.000000 -3.000000 1.000000 5.000000
	1.000000 -2.000000 -2.000000 -3.000000
	3.000000 -1.000000 2.000000 0.000000
	2.000000 3.000000 2.000000 -8.000000
Determenant is equal to 135.00
Inverse matrix A^-1 is:
	0.533333 -0.000000 -0.600000 0.333333
	0.518519 -0.222222 -0.888889 0.407407
	-0.540741 -0.111111 0.955556 -0.296296
	0.192593 -0.111111 -0.244444 0.037037
Conditionality of A is 23.77
Solution is:
	x1=2.00000
	x2=1.00000
	x3=-3.00000
	x4=1.00000
Difference is equal to 0.000000
----------------------------------------------


#### Метод Гаусса с выбором главного элемента

In [222]:
!./solver < input

Use default problems?(0-3 yes; 4 - specific): 
Types:
1 - relaxation method
0 - simple methods
Which type? Use algorithm with leading element?(1/0) 
--------FIND_THE_MAIN_ELEMENT SOLUTION--------
Linear system is is:
	x1*4.00 - x2*3.00 + x3*1.00 + x4*5.00 = 7.00
	x1*1.00 - x2*2.00 - x3*2.00 - x4*3.00 = 3.00
	x1*3.00 - x2*1.00 + x3*2.00 + x4*-0.00 = -1.00
	x1*2.00 + x2*3.00 + x3*2.00 - x4*8.00 = -7.00
A matrix is:
	4.000000 -3.000000 1.000000 5.000000
	1.000000 -2.000000 -2.000000 -3.000000
	3.000000 -1.000000 2.000000 0.000000
	2.000000 3.000000 2.000000 -8.000000
Determenant is equal to 135.00
Inverse matrix A^-1 is:
	0.533333 -0.000000 -0.600000 0.333333
	0.518519 -0.222222 -0.888889 0.407407
	-0.540741 -0.111111 0.955556 -0.296296
	0.192593 -0.111111 -0.244444 0.037037
Conditionality of A is 23.77
Solution is:
	x1=2.00000
	x2=1.00000
	x3=-3.00000
	x4=1.00000
Difference is equal to 0.000000
----------------------------------------------


### Test 2

In [223]:
A = np.array([
    [2, -2, 3, -1],
    [1, 2, -1, 1],
    [4, -10, 5, -5],
    [2, -14, 7, -12]
])
b = np.array([1, 1, 1, -1])
for x in np.linalg.solve(A, b):
    print("%lf" % x, end='\n')
print("Det", end=' ')
print(np.linalg.det(A))
print("A^-1", end='\n')
print(np.linalg.inv(A))
print("Condit", end=' ')
print(np.linalg.norm(A)*np.linalg.norm(np.linalg.inv(A)))

0.666667
0.166667
0.000000
-0.000000
Det 180.0
A^-1
[[ 0.          0.55555556  0.11111111  0.        ]
 [ 0.25        0.25555556 -0.23888889  0.1       ]
 [ 0.5        -0.33333333 -0.16666667  0.        ]
 [-0.         -0.4         0.2        -0.2       ]]
Condit 25.856059298917458


#### Метод Гаусса

In [226]:
!./solver < input

Use default problems?(0-3 yes; 4 - specific): 
Types:
1 - relaxation method
0 - simple methods
Which type? Use algorithm with leading element?(1/0) 
---------SIMPLE_GAUSS_METHOD SOLUTION---------
Linear system is is:
	x1*2.00 - x2*2.00 + x3*3.00 - x4*1.00 = 1.00
	x1*1.00 + x2*2.00 - x3*1.00 + x4*1.00 = 1.00
	x1*4.00 - x2*10.00 + x3*5.00 - x4*5.00 = 1.00
	x1*2.00 - x2*14.00 + x3*7.00 - x4*12.00 = -1.00
A matrix is:
	2.000000 -2.000000 3.000000 -1.000000
	1.000000 2.000000 -1.000000 1.000000
	4.000000 -10.000000 5.000000 -5.000000
	2.000000 -14.000000 7.000000 -12.000000
Determenant is equal to 180.00
Inverse matrix A^-1 is:
	0.000000 0.555556 0.111111 -0.000000
	0.250000 0.255556 -0.238889 0.100000
	0.500000 -0.333333 -0.166667 -0.000000
	-0.000000 -0.400000 0.200000 -0.200000
Conditionality of A is 25.86
Solution is:
	x1=0.66667
	x2=0.16667
	x3=-0.00000
	x4=-0.00000
Difference is equal to 0.000000
----------------------------------------------


#### Метод Гаусса с выбором главного элемента

In [227]:
!./solver < input

Use default problems?(0-3 yes; 4 - specific): 
Types:
1 - relaxation method
0 - simple methods
Which type? Use algorithm with leading element?(1/0) 
--------FIND_THE_MAIN_ELEMENT SOLUTION--------
Linear system is is:
	x1*2.00 - x2*2.00 + x3*3.00 - x4*1.00 = 1.00
	x1*1.00 + x2*2.00 - x3*1.00 + x4*1.00 = 1.00
	x1*4.00 - x2*10.00 + x3*5.00 - x4*5.00 = 1.00
	x1*2.00 - x2*14.00 + x3*7.00 - x4*12.00 = -1.00
A matrix is:
	2.000000 -2.000000 3.000000 -1.000000
	1.000000 2.000000 -1.000000 1.000000
	4.000000 -10.000000 5.000000 -5.000000
	2.000000 -14.000000 7.000000 -12.000000
Determenant is equal to 180.00
Inverse matrix A^-1 is:
	0.000000 0.555556 0.111111 -0.000000
	0.250000 0.255556 -0.238889 0.100000
	0.500000 -0.333333 -0.166667 0.000000
	0.000000 -0.400000 0.200000 -0.200000
Conditionality of A is 25.86
Solution is:
	x1=0.66667
	x2=0.16667
	x3=-0.00000
	x4=0.00000
Difference is equal to 0.000000
----------------------------------------------


### Test 3

In [228]:
A = np.array([
    [2, -1, 3, 4],
    [4, -1, 5, 6],
    [6, -3, 5, 8],
    [8, -4, 9, 10]
])
b = np.array([5, 7, 9, 11])
for x in np.linalg.solve(A, b):
    print("%lf" % x, end='\n')
print("Det", end=' ')
print(np.linalg.det(A))
print("A^-1", end='\n')
print(np.linalg.inv(A))
print("Condit", end=' ')
print(np.linalg.norm(A)*np.linalg.norm(np.linalg.inv(A)))

-0.500000
0.000000
-0.000000
1.500000
Det 23.999999999999993
A^-1
[[-1.25000000e+00  5.00000000e-01  2.50000000e-01 -1.66533454e-16]
 [-6.66666667e-01  1.00000000e+00  5.55111512e-17 -3.33333333e-01]
 [ 1.66666667e-01 -0.00000000e+00 -5.00000000e-01  3.33333333e-01]
 [ 5.83333333e-01  0.00000000e+00  2.50000000e-01 -3.33333333e-01]]
Condit 46.68690037544436


#### Метод Гаусса

In [229]:
!./solver < input

Use default problems?(0-3 yes; 4 - specific): 
Types:
1 - relaxation method
0 - simple methods
Which type? Use algorithm with leading element?(1/0) 
---------SIMPLE_GAUSS_METHOD SOLUTION---------
Linear system is is:
	x1*2.00 - x2*1.00 + x3*3.00 + x4*4.00 = 5.00
	x1*4.00 - x2*1.00 + x3*5.00 + x4*6.00 = 7.00
	x1*6.00 - x2*3.00 + x3*5.00 + x4*8.00 = 9.00
	x1*8.00 - x2*4.00 + x3*9.00 + x4*10.00 = 11.00
A matrix is:
	2.000000 -1.000000 3.000000 4.000000
	4.000000 -1.000000 5.000000 6.000000
	6.000000 -3.000000 5.000000 8.000000
	8.000000 -4.000000 9.000000 10.000000
Determenant is equal to 24.00
Inverse matrix A^-1 is:
	-1.250000 0.500000 0.250000 -0.000000
	-0.666667 1.000000 -0.000000 -0.333333
	0.166667 -0.000000 -0.500000 0.333333
	0.583333 0.000000 0.250000 -0.333333
Conditionality of A is 46.69
Solution is:
	x1=-0.50000
	x2=0.00000
	x3=0.00000
	x4=1.50000
Difference is equal to 0.000000
----------------------------------------------


#### Метод Гаусса с выбором главного элемента

In [230]:
!./solver < input

Use default problems?(0-3 yes; 4 - specific): 
Types:
1 - relaxation method
0 - simple methods
Which type? Use algorithm with leading element?(1/0) 
--------FIND_THE_MAIN_ELEMENT SOLUTION--------
Linear system is is:
	x1*2.00 - x2*1.00 + x3*3.00 + x4*4.00 = 5.00
	x1*4.00 - x2*1.00 + x3*5.00 + x4*6.00 = 7.00
	x1*6.00 - x2*3.00 + x3*5.00 + x4*8.00 = 9.00
	x1*8.00 - x2*4.00 + x3*9.00 + x4*10.00 = 11.00
A matrix is:
	2.000000 -1.000000 3.000000 4.000000
	4.000000 -1.000000 5.000000 6.000000
	6.000000 -3.000000 5.000000 8.000000
	8.000000 -4.000000 9.000000 10.000000
Determenant is equal to 24.00
Inverse matrix A^-1 is:
	-1.250000 0.500000 0.250000 -0.000000
	-0.666667 1.000000 0.000000 -0.333333
	0.166667 0.000000 -0.500000 0.333333
	0.583333 -0.000000 0.250000 -0.333333
Conditionality of A is 46.69
Solution is:
	x1=-0.50000
	x2=-0.00000
	x3=0.00000
	x4=1.50000
Difference is equal to 0.000000
----------------------------------------------


### Test 4

In [3]:
def A_gen(i, j, m, n):
    if i == j:
        return n+m*m + (j/m) + (i/n)
    return (i+j)/(m+n)
def b_gen(i, m, n):
    return m*i+n

In [6]:
n = 30
m = 20
A = np.random.random(size=[n,n])
b = np.random.random(size=n)
for i in range(n):
    for j in range(n):
        A[i][j] = A_gen(i, j, m, n)
    b[i] = b_gen(i, m, n)

In [7]:
for x in np.linalg.solve(A, b):
    print("%lf" % x, end='\n')
print("Det", end=' ')
print(np.linalg.det(A))
print("A^-1", end='\n')
C = np.linalg.inv(A)
for i in range(n):
    for j in range(n):
        print("%lf" % C[i][j], end=' ')
    print("\n")
print("Condit", end=' ')
print(np.linalg.norm(A)*np.linalg.norm(np.linalg.inv(A)))

0.050671
0.096183
0.141686
0.187180
0.232665
0.278140
0.323606
0.369064
0.414512
0.459950
0.505380
0.550801
0.596212
0.641614
0.687007
0.732391
0.777766
0.823132
0.868489
0.913836
0.959174
1.004504
1.049824
1.095135
1.140437
1.185729
1.231013
1.276288
1.321553
1.366810
Det 1.0969996638681652e+79
A^-1
0.002326 -0.000000 -0.000000 -0.000000 -0.000000 -0.000000 -0.000001 -0.000001 -0.000001 -0.000001 -0.000001 -0.000001 -0.000001 -0.000001 -0.000001 -0.000002 -0.000002 -0.000002 -0.000002 -0.000002 -0.000002 -0.000002 -0.000002 -0.000002 -0.000002 -0.000003 -0.000003 -0.000003 -0.000003 -0.000003 

-0.000000 0.002325 -0.000000 -0.000000 -0.000000 -0.000001 -0.000001 -0.000001 -0.000001 -0.000001 -0.000001 -0.000001 -0.000001 -0.000001 -0.000002 -0.000002 -0.000002 -0.000002 -0.000002 -0.000002 -0.000002 -0.000002 -0.000002 -0.000002 -0.000003 -0.000003 -0.000003 -0.000003 -0.000003 -0.000003 

-0.000000 -0.000000 0.002325 -0.000000 -0.000001 -0.000001 -0.000001 -0.000001 -0.000001 -0.0000

#### Метод Гаусса

In [245]:
!./solver < input

Use default problems?(0-3 yes; 4 - specific): 
Types:
1 - relaxation method
0 - simple methods
Which type? Use algorithm with leading element?(1/0) 
---------SIMPLE_GAUSS_METHOD SOLUTION---------
Linear system is is:
	x1*430.00 + x2*0.02 + x3*0.04 + x4*0.06 + x5*0.08 + x6*0.10 + x7*0.12 + x8*0.14 + x9*0.16 + x10*0.18 + x11*0.20 + x12*0.22 + x13*0.24 + x14*0.26 + x15*0.28 + x16*0.30 + x17*0.32 + x18*0.34 + x19*0.36 + x20*0.38 + x21*0.40 + x22*0.42 + x23*0.44 + x24*0.46 + x25*0.48 + x26*0.50 + x27*0.52 + x28*0.54 + x29*0.56 + x30*0.58 = 30.00
	x1*0.02 + x2*430.08 + x3*0.06 + x4*0.08 + x5*0.10 + x6*0.12 + x7*0.14 + x8*0.16 + x9*0.18 + x10*0.20 + x11*0.22 + x12*0.24 + x13*0.26 + x14*0.28 + x15*0.30 + x16*0.32 + x17*0.34 + x18*0.36 + x19*0.38 + x20*0.40 + x21*0.42 + x22*0.44 + x23*0.46 + x24*0.48 + x25*0.50 + x26*0.52 + x27*0.54 + x28*0.56 + x29*0.58 + x30*0.60 = 50.00
	x1*0.04 + x2*0.06 + x3*430.17 + x4*0.10 + x5*0.12 + x6*0.14 + x7*0.16 + x8*0.18 + x9*0.20 + x10*0.22 + x11*0.24 + x12*0.26

#### Метод Гаусса с выбором главного элемента(Исправить!)

In [246]:
!./solver < input

Use default problems?(0-3 yes; 4 - specific): 
Types:
1 - relaxation method
0 - simple methods
Which type? Use algorithm with leading element?(1/0) 
--------FIND_THE_MAIN_ELEMENT SOLUTION--------
Linear system is is:
	x1*430.00 + x2*0.02 + x3*0.04 + x4*0.06 + x5*0.08 + x6*0.10 + x7*0.12 + x8*0.14 + x9*0.16 + x10*0.18 + x11*0.20 + x12*0.22 + x13*0.24 + x14*0.26 + x15*0.28 + x16*0.30 + x17*0.32 + x18*0.34 + x19*0.36 + x20*0.38 + x21*0.40 + x22*0.42 + x23*0.44 + x24*0.46 + x25*0.48 + x26*0.50 + x27*0.52 + x28*0.54 + x29*0.56 + x30*0.58 = 30.00
	x1*0.02 + x2*430.08 + x3*0.06 + x4*0.08 + x5*0.10 + x6*0.12 + x7*0.14 + x8*0.16 + x9*0.18 + x10*0.20 + x11*0.22 + x12*0.24 + x13*0.26 + x14*0.28 + x15*0.30 + x16*0.32 + x17*0.34 + x18*0.36 + x19*0.38 + x20*0.40 + x21*0.42 + x22*0.44 + x23*0.46 + x24*0.48 + x25*0.50 + x26*0.52 + x27*0.54 + x28*0.56 + x29*0.58 + x30*0.60 = 50.00
	x1*0.04 + x2*0.06 + x3*430.17 + x4*0.10 + x5*0.12 + x6*0.14 + x7*0.16 + x8*0.18 + x9*0.20 + x10*0.22 + x11*0.24 + x12*0.26

## Тест из входного массива

### Test 5

In [247]:
A = np.random.normal(size = [100,100])
b = np.random.normal(size= 100)

In [261]:
for x in np.linalg.solve(A, b):
    print("%lf" % x, end='\n')
print("Det", end=' ')
print(np.linalg.det(A))
print("A^-1", end='\n')
C = np.linalg.inv(A)
print("-------")
for i in range(100):
    for j in range(100):
        print("%lf" % C[i][j], end=' ')
    print("\n")
print("Condit", end=' ')
print(np.linalg.norm(A)*np.linalg.norm(np.linalg.inv(A)))

2.172865
1.784203
1.849161
0.409103
-0.802841
2.325706
0.355881
-1.127663
-2.962084
-1.723490
4.607773
0.952746
2.270424
-0.151196
-0.885825
0.293611
0.598145
4.014841
5.207975
-0.659702
1.863240
-1.904820
2.784694
1.117862
1.227076
-3.164633
-0.430911
1.043237
-2.370990
-0.815036
2.443216
1.895471
2.854828
1.359022
3.486306
-0.854497
1.359940
-4.540969
1.188194
0.696276
-0.910316
3.006015
-0.848560
-2.842309
-4.855401
0.779047
-1.324041
-0.018427
2.392906
-0.274993
0.646886
-0.245233
-1.837212
-4.129816
3.929743
2.191745
-1.482786
-0.130122
0.437102
-1.204472
1.198335
2.457382
-0.593562
-0.145935
0.235245
-0.855942
-0.690904
-2.829510
-0.502698
-3.751228
1.409218
2.942970
-1.406959
-1.363498
-0.037979
1.529770
2.961914
0.848041
-2.272761
0.136689
-2.643949
-0.780956
1.065345
0.127127
0.031196
-2.662990
1.814006
-0.927682
1.040927
-1.937757
4.066648
-0.702284
-1.474456
0.906972
1.048310
1.725666
-0.774312
-1.135326
0.429008
2.120696
Det -7.50117687865587e+77
A^-1
-------
0.062363 -0.13

#### Метод Гаусса

In [262]:
!./solver < input

Use default problems?(0-3 yes; 4 - specific): 
Types:
1 - relaxation method
0 - simple methods
Which type? Enter the size of matrix: Read matrix form file(y/n): Enter path to file: Use algorithm with leading element?(1/0) 
---------SIMPLE_GAUSS_METHOD SOLUTION---------
Linear system is is:
	x1*0.07 + x2*0.99 + x3*0.03 + x4*1.34 - x5*1.53 + x6*1.43 - x7*0.41 - x8*0.03 - x9*0.45 + x10*0.28 - x11*0.97 + x12*0.48 - x13*1.12 - x14*0.35 - x15*1.04 - x16*1.20 - x17*0.49 - x18*0.08 + x19*0.34 + x20*0.90 + x21*0.29 + x22*1.13 + x23*0.96 + x24*0.48 + x25*0.98 + x26*0.29 + x27*1.87 + x28*1.33 - x29*0.57 + x30*0.05 - x31*1.67 - x32*0.74 - x33*1.46 - x34*1.12 + x35*0.06 - x36*0.96 - x37*0.97 + x38*1.09 + x39*0.60 + x40*1.26 - x41*0.22 + x42*0.61 - x43*0.10 + x44*0.02 - x45*0.49 + x46*0.52 + x47*0.00 - x48*0.34 - x49*0.32 + x50*0.02 + x51*1.06 + x52*0.36 + x53*0.20 - x54*0.41 - x55*0.31 - x56*0.29 - x57*0.13 - x58*0.52 - x59*0.56 - x60*0.90 - x61*0.04 - x62*0.51 + x63*1.87 + x64*0.35 + x65*0.69 - x6

#### Метод Гаусса с выбором главного элемента

In [263]:
!./solver < input

Use default problems?(0-3 yes; 4 - specific): 
Types:
1 - relaxation method
0 - simple methods
Which type? Enter the size of matrix: Read matrix form file(y/n): Enter path to file: Use algorithm with leading element?(1/0) 
--------FIND_THE_MAIN_ELEMENT SOLUTION--------
Linear system is is:
	x1*0.07 + x2*0.99 + x3*0.03 + x4*1.34 - x5*1.53 + x6*1.43 - x7*0.41 - x8*0.03 - x9*0.45 + x10*0.28 - x11*0.97 + x12*0.48 - x13*1.12 - x14*0.35 - x15*1.04 - x16*1.20 - x17*0.49 - x18*0.08 + x19*0.34 + x20*0.90 + x21*0.29 + x22*1.13 + x23*0.96 + x24*0.48 + x25*0.98 + x26*0.29 + x27*1.87 + x28*1.33 - x29*0.57 + x30*0.05 - x31*1.67 - x32*0.74 - x33*1.46 - x34*1.12 + x35*0.06 - x36*0.96 - x37*0.97 + x38*1.09 + x39*0.60 + x40*1.26 - x41*0.22 + x42*0.61 - x43*0.10 + x44*0.02 - x45*0.49 + x46*0.52 + x47*0.00 - x48*0.34 - x49*0.32 + x50*0.02 + x51*1.06 + x52*0.36 + x53*0.20 - x54*0.41 - x55*0.31 - x56*0.29 - x57*0.13 - x58*0.52 - x59*0.56 - x60*0.90 - x61*0.04 - x62*0.51 + x63*1.87 + x64*0.35 + x65*0.69 - x6

# 2nd Part

## 4 Теста из примеров

### Test 1

In [264]:
A = np.array([
    [4, -3, 1, 5],
    [1, -2, -2, -3],
    [3, -1, 2, 0],
    [2, 3, 2, -8]
])
b = np.array([7, 3, -1, -7])
for x in np.linalg.solve(A, b):
    print("%lf" % x, end='\n')
print("Det", end=' ')
print(np.linalg.det(A))
print("A^-1", end='\n')
print(np.linalg.inv(A))
print("Condit", end=' ')
print(np.linalg.norm(A)*np.linalg.norm(np.linalg.inv(A)))

2.000000
1.000000
-3.000000
1.000000
Det 134.99999999999991
A^-1
[[ 0.53333333  0.         -0.6         0.33333333]
 [ 0.51851852 -0.22222222 -0.88888889  0.40740741]
 [-0.54074074 -0.11111111  0.95555556 -0.2962963 ]
 [ 0.19259259 -0.11111111 -0.24444444  0.03703704]]
Condit 23.773069800440698


#### Метод верхней релаксации

In [265]:
!./solver < relaxinput.txt

Use default problems?(0-3 yes; 4 - specific): 
Types:
1 - relaxation method
0 - simple methods
Which type? Save the best result?(1/0) Print all iterations? (1/0) Use specific epsilon? (1/0) Use specific omega?(1/0) 
-------------RELAXATION SOLUTION--------------
Linear system is is:
	x1*30.00 - x2*11.00 + x3*12.00 + x4*1.00 = 14.00
	-x1*11.00 + x2*23.00 + x3*5.00 - x4*33.00 = -47.00
	x1*12.00 + x2*5.00 + x3*13.00 - x4*5.00 = -15.00
	x1*1.00 - x2*33.00 - x3*5.00 + x4*98.00 = 82.00
A matrix is:
	30.000000 -11.000000 12.000000 1.000000
	-11.000000 23.000000 5.000000 -33.000000
	12.000000 5.000000 13.000000 -5.000000
	1.000000 -33.000000 -5.000000 98.000000
Determenant is equal to 18225.00
Inverse matrix A^-1 is:
	0.755556 0.945679 -0.960494 0.261728
	0.945679 1.274348 -1.225789 0.356927
	-0.960494 -1.225789 1.305624 -0.336351
	0.261728 0.356927 -0.336351 0.110562
Conditionality of A is 395.59
Iterations:

-------------------------
Iteration №1
	omega: 0.100000
	Iterations done: 6900
	Diff

### Test 2

In [267]:
A = np.array([
    [2, -2, 3, -1],
    [1, 2, -1, 1],
    [4, -10, 5, -5],
    [2, -14, 7, -12]
])
b = np.array([1, 1, 1, -1])
for x in np.linalg.solve(A, b):
    print("%lf" % x, end='\n')
print("Det", end=' ')
print(np.linalg.det(A))
print("A^-1", end='\n')
print(np.linalg.inv(A))
print("Condit", end=' ')
print(np.linalg.norm(A)*np.linalg.norm(np.linalg.inv(A)))

0.666667
0.166667
0.000000
-0.000000
Det 180.0
A^-1
[[ 0.          0.55555556  0.11111111  0.        ]
 [ 0.25        0.25555556 -0.23888889  0.1       ]
 [ 0.5        -0.33333333 -0.16666667  0.        ]
 [-0.         -0.4         0.2        -0.2       ]]
Condit 25.856059298917458


#### Метод верхней релаксации

In [266]:
!./solver < relaxinput.txt

Use default problems?(0-3 yes; 4 - specific): 
Types:
1 - relaxation method
0 - simple methods
Which type? Save the best result?(1/0) Print all iterations? (1/0) Use specific epsilon? (1/0) Use specific omega?(1/0) 
-------------RELAXATION SOLUTION--------------
Linear system is is:
	x1*25.00 - x2*70.00 + x3*39.00 - x4*45.00 = 5.00
	-x1*70.00 + x2*304.00 - x3*156.00 + x4*222.00 = 4.00
	x1*39.00 - x2*156.00 + x3*84.00 - x4*113.00 = 0.00
	-x1*45.00 + x2*222.00 - x3*113.00 + x4*171.00 = 7.00
A matrix is:
	25.000000 -70.000000 39.000000 -45.000000
	-70.000000 304.000000 -156.000000 222.000000
	39.000000 -156.000000 84.000000 -113.000000
	-45.000000 222.000000 -113.000000 171.000000
Determenant is equal to 32400.00
Inverse matrix A^-1 is:
	0.320988 0.115432 -0.203704 -0.200000
	0.115432 0.194877 0.079630 -0.170000
	-0.203704 0.079630 0.388889 0.100000
	-0.200000 -0.170000 0.100000 0.240000
Conditionality of A is 448.29
Iterations:

-------------------------
Iteration №1
	omega: 0.100000
	It

### Test 3

In [268]:
A = np.array([
    [2, -1, 3, 4],
    [4, -1, 5, 6],
    [6, -3, 5, 8],
    [8, -4, 9, 10]
])
b = np.array([5, 7, 9, 11])
for x in np.linalg.solve(A, b):
    print("%lf" % x, end='\n')
print("Det", end=' ')
print(np.linalg.det(A))
print("A^-1", end='\n')
print(np.linalg.inv(A))
print("Condit", end=' ')
print(np.linalg.norm(A)*np.linalg.norm(np.linalg.inv(A)))

-0.500000
0.000000
-0.000000
1.500000
Det 23.999999999999993
A^-1
[[-1.25000000e+00  5.00000000e-01  2.50000000e-01 -1.66533454e-16]
 [-6.66666667e-01  1.00000000e+00  5.55111512e-17 -3.33333333e-01]
 [ 1.66666667e-01 -0.00000000e+00 -5.00000000e-01  3.33333333e-01]
 [ 5.83333333e-01  0.00000000e+00  2.50000000e-01 -3.33333333e-01]]
Condit 46.68690037544436


#### Метод верхней релаксации

In [269]:
!./solver < relaxinput.txt

Use default problems?(0-3 yes; 4 - specific): 
Types:
1 - relaxation method
0 - simple methods
Which type? Save the best result?(1/0) Print all iterations? (1/0) Use specific epsilon? (1/0) Use specific omega?(1/0) 
-------------RELAXATION SOLUTION--------------
Linear system is is:
	x1*120.00 - x2*56.00 + x3*128.00 + x4*160.00 = 180.00
	-x1*56.00 + x2*27.00 - x3*59.00 - x4*74.00 = -83.00
	x1*128.00 - x2*59.00 + x3*140.00 + x4*172.00 = 194.00
	x1*160.00 - x2*74.00 + x3*172.00 + x4*216.00 = 244.00
A matrix is:
	120.000000 -56.000000 128.000000 160.000000
	-56.000000 27.000000 -59.000000 -74.000000
	128.000000 -59.000000 140.000000 172.000000
	160.000000 -74.000000 172.000000 216.000000
Determenant is equal to 576.00
Inverse matrix A^-1 is:
	1.875000 1.333333 -0.333333 -0.666667
	1.333333 1.555556 -0.222222 -0.277778
	-0.333333 -0.222222 0.388889 -0.138889
	-0.666667 -0.277778 -0.138889 0.513889
Conditionality of A is 1677.09
Iterations:

-------------------------
Iteration №1
	omega: 0.

### Test 4

In [270]:
def A_gen(i, j, m, n):
    if i == j:
        return n+m*m + (j/m) + (i/n)
    return (i+j)/(m+n)
def b_gen(i, m, n):
    return m*i+n

In [271]:
n = 30
m = 20
A = np.random.random(size=[n,n])
b = np.random.random(size=n)
for i in range(n):
    for j in range(n):
        A[i][j] = A_gen(i, j, m, n)
    b[i] = b_gen(i, m, n)

In [272]:
for x in np.linalg.solve(A, b):
    print("%lf" % x, end='\n')
print("Det", end=' ')
print(np.linalg.det(A))
print("A^-1", end='\n')
C = np.linalg.inv(A)
for i in range(n):
    for j in range(n):
        print("%lf" % C[i][j], end=' ')
    print("\n")
print("Condit", end=' ')
print(np.linalg.norm(A)*np.linalg.norm(np.linalg.inv(A)))

0.050671
0.096183
0.141686
0.187180
0.232665
0.278140
0.323606
0.369064
0.414512
0.459950
0.505380
0.550801
0.596212
0.641614
0.687007
0.732391
0.777766
0.823132
0.868489
0.913836
0.959174
1.004504
1.049824
1.095135
1.140437
1.185729
1.231013
1.276288
1.321553
1.366810
Det 1.0969996638681652e+79
A^-1
0.002326 -0.000000 -0.000000 -0.000000 -0.000000 -0.000000 -0.000001 -0.000001 -0.000001 -0.000001 -0.000001 -0.000001 -0.000001 -0.000001 -0.000001 -0.000002 -0.000002 -0.000002 -0.000002 -0.000002 -0.000002 -0.000002 -0.000002 -0.000002 -0.000002 -0.000003 -0.000003 -0.000003 -0.000003 -0.000003 

-0.000000 0.002325 -0.000000 -0.000000 -0.000000 -0.000001 -0.000001 -0.000001 -0.000001 -0.000001 -0.000001 -0.000001 -0.000001 -0.000001 -0.000002 -0.000002 -0.000002 -0.000002 -0.000002 -0.000002 -0.000002 -0.000002 -0.000002 -0.000002 -0.000003 -0.000003 -0.000003 -0.000003 -0.000003 -0.000003 

-0.000000 -0.000000 0.002325 -0.000000 -0.000001 -0.000001 -0.000001 -0.000001 -0.000001 -0.0000

#### Метод верхней релаксации

In [273]:
!./solver < relaxinput.txt

Use default problems?(0-3 yes; 4 - specific): 
Types:
1 - relaxation method
0 - simple methods
Which type? Save the best result?(1/0) Print all iterations? (1/0) Use specific epsilon? (1/0) Use specific omega?(1/0) 
-------------RELAXATION SOLUTION--------------
Linear system is is:
	x1*430.00 + x2*0.02 + x3*0.04 + x4*0.06 + x5*0.08 + x6*0.10 + x7*0.12 + x8*0.14 + x9*0.16 + x10*0.18 + x11*0.20 + x12*0.22 + x13*0.24 + x14*0.26 + x15*0.28 + x16*0.30 + x17*0.32 + x18*0.34 + x19*0.36 + x20*0.38 + x21*0.40 + x22*0.42 + x23*0.44 + x24*0.46 + x25*0.48 + x26*0.50 + x27*0.52 + x28*0.54 + x29*0.56 + x30*0.58 = 30.00
	x1*0.02 + x2*430.08 + x3*0.06 + x4*0.08 + x5*0.10 + x6*0.12 + x7*0.14 + x8*0.16 + x9*0.18 + x10*0.20 + x11*0.22 + x12*0.24 + x13*0.26 + x14*0.28 + x15*0.30 + x16*0.32 + x17*0.34 + x18*0.36 + x19*0.38 + x20*0.40 + x21*0.42 + x22*0.44 + x23*0.46 + x24*0.48 + x25*0.50 + x26*0.52 + x27*0.54 + x28*0.56 + x29*0.58 + x30*0.60 = 50.00
	x1*0.04 + x2*0.06 + x3*430.17 + x4*0.10 + x5*0.12 + x6*

### Test 5

In [274]:
A = np.random.normal(size = [100,100])
b = np.random.normal(size= 100)

In [277]:
for x in np.linalg.solve(A, b):
    print("%lf" % x, end='\n')
print("Det", end=' ')
print(np.linalg.det(A))
print("A^-1", end='\n')
C = np.linalg.inv(A)
print("-------")
for i in range(100):
    for j in range(100):
        print("%lf" % C[i][j], end=' ')
    print("\n")
print("Condit", end=' ')
print(np.linalg.norm(A)*np.linalg.norm(np.linalg.inv(A)))

1.010938
0.210736
0.149478
-0.033894
-0.934853
-0.661166
-1.234170
-0.291827
-0.203389
-1.147975
-0.370047
1.439105
1.331505
-0.655679
0.851670
-0.153624
-0.329038
-2.133585
-0.446981
0.381791
-0.872940
1.172636
0.383337
0.580990
1.123335
-1.950257
0.479429
0.649907
0.626545
1.116691
0.930273
0.298061
-0.464929
0.726446
-0.890028
-0.585970
0.127270
0.821477
1.235740
0.100603
-0.244655
0.372645
0.216649
0.405443
-0.579202
-0.322383
0.764519
1.333778
-0.193150
1.178516
-0.424831
-0.796289
-0.964728
0.232848
-0.126835
0.175922
1.549733
-1.309521
0.327031
0.345127
1.254148
-1.206108
0.332535
-0.314690
0.691014
-0.992157
0.605727
0.406369
-0.519078
0.190712
0.111281
-0.604517
0.445617
0.743338
0.214170
0.373016
0.252097
0.514441
0.653704
-0.131226
-1.520325
0.916739
-1.367783
0.723250
-0.182115
-0.400289
0.270730
-0.305949
1.067474
-0.162442
0.348700
-1.548927
0.927600
-1.295952
0.548034
-0.174744
0.436576
0.919286
-0.297566
-0.029806
Det -1.4102074988348615e+78
A^-1
-------
0.297662 -0.172

#### Метод верхней релаксации

In [278]:
!./solver < relaxinput.txt

Use default problems?(0-3 yes; 4 - specific): 
Types:
1 - relaxation method
0 - simple methods
Which type? Enter the size of matrix: Read matrix form file(y/n): Enter path to file: Save the best result?(1/0) Print all iterations? (1/0) Use specific epsilon? (1/0) Use specific omega?(1/0) 
-------------RELAXATION SOLUTION--------------
Matrix must be positive definite!
Making A^T*Ax = A^T*bLinear system is is:
	x1*100.60 - x2*5.50 - x3*4.69 - x4*2.25 + x5*8.13 + x6*5.04 + x7*7.67 + x8*10.48 - x9*5.09 + x10*4.17 - x11*9.13 - x12*8.06 + x13*3.07 - x14*0.24 + x15*0.39 - x16*4.90 + x17*5.19 + x18*6.09 + x19*5.35 + x20*1.01 - x21*14.32 - x22*1.96 - x23*3.81 - x24*10.86 - x25*7.36 - x26*8.88 - x27*4.78 - x28*0.42 + x29*19.16 + x30*10.19 + x31*0.79 - x32*5.23 + x33*0.92 - x34*7.01 + x35*9.48 + x36*20.60 - x37*15.47 - x38*0.05 + x39*23.02 + x40*3.08 + x41*19.56 + x42*22.01 - x43*4.44 - x44*11.61 + x45*9.71 - x46*2.44 + x47*12.25 - x48*0.23 + x49*20.35 + x50*7.15 + x51*4.33 + x52*6.24 - x53*0.36

# Устойчивость

In [88]:
A = np.random.sample(size = [100,100])
b = np.random.sample(size= 100)

## Рассмотрим матрицу Гильберта

In [180]:
for i in range(100):
    for j in range(100):
        A[i][j] = 1/(i+j+1)
        #print(A[i][j], end=' ')
    b[i] = i
print("------")
for x in np.linalg.solve(A, b):
    pass
    #    print("%lf" % x, end='\n')
print("Condit", end=' ')
print(np.linalg.norm(A)*np.linalg.norm(np.linalg.inv(A)))

------
Condit 2.4193152122584175e+19


In [154]:
!./solver < input

Use default problems?(0-3 yes; 4 - specific): 
Types:
1 - relaxation method
0 - simple methods
Which type? Enter the size of matrix: Read matrix form file(y/n): Enter path to file: Use algorithm with leading element?(1/0) 
---------SIMPLE_GAUSS_METHOD SOLUTION---------
Linear system is is:
	x1*1.00 + x2*0.50 + x3*0.33 + x4*0.25 + x5*0.20 + x6*0.17 + x7*0.14 + x8*0.12 + x9*0.11 + x10*0.10 + x11*0.09 + x12*0.08 + x13*0.08 + x14*0.07 + x15*0.07 + x16*0.06 + x17*0.06 + x18*0.06 + x19*0.05 + x20*0.05 + x21*0.05 + x22*0.05 + x23*0.04 + x24*0.04 + x25*0.04 + x26*0.04 + x27*0.04 + x28*0.04 + x29*0.03 + x30*0.03 + x31*0.03 + x32*0.03 + x33*0.03 + x34*0.03 + x35*0.03 + x36*0.03 + x37*0.03 + x38*0.03 + x39*0.03 + x40*0.03 + x41*0.02 + x42*0.02 + x43*0.02 + x44*0.02 + x45*0.02 + x46*0.02 + x47*0.02 + x48*0.02 + x49*0.02 + x50*0.02 + x51*0.02 + x52*0.02 + x53*0.02 + x54*0.02 + x55*0.02 + x56*0.02 + x57*0.02 + x58*0.02 + x59*0.02 + x60*0.02 + x61*0.02 + x62*0.02 + x63*0.02 + x64*0.02 + x65*0.02 + x6

In [181]:
n0 = np.linalg.norm(b)
vect = np.array(b)
for i in range(100):
    b[i] += 0.01
vect = vect - b
n1 = np.linalg.norm(vect)
l0 = np.linalg.solve(A, b)
for i in range(100):
    b[i] -= 0.01
l1 = np.linalg.solve(A, b)

In [155]:
!./solver < input

Use default problems?(0-3 yes; 4 - specific): 
Types:
1 - relaxation method
0 - simple methods
Which type? Enter the size of matrix: Read matrix form file(y/n): Enter path to file: Use algorithm with leading element?(1/0) 
---------SIMPLE_GAUSS_METHOD SOLUTION---------
Linear system is is:
	x1*1.00 + x2*0.50 + x3*0.33 + x4*0.25 + x5*0.20 + x6*0.17 + x7*0.14 + x8*0.12 + x9*0.11 + x10*0.10 + x11*0.09 + x12*0.08 + x13*0.08 + x14*0.07 + x15*0.07 + x16*0.06 + x17*0.06 + x18*0.06 + x19*0.05 + x20*0.05 + x21*0.05 + x22*0.05 + x23*0.04 + x24*0.04 + x25*0.04 + x26*0.04 + x27*0.04 + x28*0.04 + x29*0.03 + x30*0.03 + x31*0.03 + x32*0.03 + x33*0.03 + x34*0.03 + x35*0.03 + x36*0.03 + x37*0.03 + x38*0.03 + x39*0.03 + x40*0.03 + x41*0.02 + x42*0.02 + x43*0.02 + x44*0.02 + x45*0.02 + x46*0.02 + x47*0.02 + x48*0.02 + x49*0.02 + x50*0.02 + x51*0.02 + x52*0.02 + x53*0.02 + x54*0.02 + x55*0.02 + x56*0.02 + x57*0.02 + x58*0.02 + x59*0.02 + x60*0.02 + x61*0.02 + x62*0.02 + x63*0.02 + x64*0.02 + x65*0.02 + x6

In [189]:
l = l0 - l1
#print(n1)
#print(n0)
print(n1)
ndif = np.linalg.norm(l)
ndef = np.linalg.norm(l0)
#print(ndif)
#print(ndef)
print(ndif)

0.10000000000001424
3348161359.9039965


In [170]:
np.linalg.cond(A, p = 2)

2.209807011860762e+19

In [182]:
l0 = np.array([
    -51080.97234,
8896656.69578,
-376119944.13745,
6672140733.47629,
-60598460115.56357,
302877419806.21735,
-805742221978.76025,
799094599101.56301,
1068939618630.58767,
-2943000254134.59640,
-218715278368.13316,
5192593353734.75785,
-1438785028316.34934,
-6042839511106.54816,
2971549916052.35614,
4861601587959.00668,
-3805799323332.51232,
-1622596763325.13045,
900136241012.15137,
-1196936411142.99356,
3451405846169.67692,
4780861525505.00524,
-3883253746061.39809,
-6568738771602.46417,
4141478000066.11825,
-1034395654628.73130,
-6107943566800.49346,
3627340755965.19833,
7220589705649.74318,
-2007351459881.97274,
1542843082259.27781,
1724730975175.14722,
-2427990206771.99050,
-67409653476.59394,
1065965865131.57072,
-4308680413278.02480,
-7025040319186.44129,
5514712220537.23899,
2615052233014.30632,
-5777150941514.13100,
879864385807.85977,
4391476094391.35639,
1411560553648.40539,
193086557372.09335,
426850460942.37631,
-925558494531.96534,
-6533325612664.50370,
6113860732585.58900,
8707300151841.81064,
-1048045416811.32075,
-7157732368940.44756,
2836848209521.53430,
5471116274606.42930,
-6069878101146.37275,
-6659734735722.11797,
-398419375641.89587,
2562420930396.10999,
-3276013444977.38347,
-2239562358277.27103,
-5059378761333.86435,
-268293214435.41612,
6039970914095.79973,
5950357999627.75474,
-884460737418.35184,
-400097482484.85214,
8668732427875.47672,
4634990108944.02425,
-7880831900217.96054,
-3616596107327.84578,
7809998859987.76561,
1088355409074.02136,
-6363602163699.80241,
612540309528.99698,
-188062488716.24565,
-3192230240529.46135,
-8399723387.27214,
1814335878313.74121,
-1181929378301.22090,
-8343631693703.57530,
-490931090757.72856,
5477379674531.84657,
24881674789.29571,
-13079609596908.43674,
5518939261972.37201,
12392204761775.22772,
1411059746125.27543,
-1475364332866.01213,
-3759145974195.53903,
3787812253714.72456,
3143414284647.69682,
6365329666322.78478,
-7530453094437.25871,
-5667908745479.38145,
-681660305110.56329,
6351609011641.81199,
-2750701446593.19468,
-3329182039700.81425,
1128650402267.98294,
-4567461305079.76137,
5368145960133.37713
])

In [183]:
l1 = np.array([
    -51084.78396,
8897321.06365,
-376148054.29286,
6672639843.87417,
-60602998000.21222,
302900131295.99263,
-805802768531.94754,
799155035297.39822,
1069019054676.17972,
-2943221175757.88375,
-218730252440.28008,
5192982520142.14751,
-1438894992843.46861,
-6043291305570.19539,
2971774543479.57851,
4861963870494.69242,
-3806086817288.26482,
-1622716303709.78243,
900205900997.15900,
-1197024174250.48634,
3451664658356.88672,
4781216187833.95986,
-3883550136120.42308,
-6569231165497.29752,
4141790379966.68353,
-1034472561533.78699,
-6108396926277.54979,
3627618160546.13138,
7221131176140.02369,
-2007504364784.62225,
1542957211079.28502,
1724856754740.74792,
-2428175044748.86344,
-67417321501.67311,
1066044339423.84010,
-4309005348587.49988,
-7025563104256.09350,
5515129496297.45439,
2615248589059.06152,
-5777581629792.52124,
879934611452.23437,
4391806587873.63191,
1411664084153.42106,
193098078445.27147,
426881756365.01650,
-925627877459.89479,
-6533811469828.12469,
6114323525516.45724,
8707950466787.69537,
-1048129549362.33242,
-7158272846420.98652,
2837060234346.92984,
5471520526535.43576,
-6070337397560.87964,
-6660233701499.89314,
-398446471760.74392,
2562611966419.27155,
-3276259349694.11494,
-2239727715306.51684,
-5059751638082.81212,
-268303987574.78032,
6040431201543.58239,
5950807256114.57887,
-884527231775.17656,
-400127171740.40228,
8669379022964.29666,
4635329569771.19199,
-7881428465249.56005,
-3616865913801.23457,
7810583267322.52068,
1088431670327.53995,
-6364081595828.65213,
612586979681.65835,
-188077016240.08228,
-3192469337790.30904,
-8400353735.23382,
1814470790400.89757,
-1182020975647.03624,
-8344257628199.86017,
-490964918427.73681,
5477792316339.83142,
24883902789.94622,
-13080583477232.70557,
5519363382090.36221,
12393133956328.17057,
1411162414537.78431,
-1475477823128.20939,
-3759425563621.57406,
3788096244218.77448,
3143647557199.04267,
6365800819614.22131,
-7531022435464.43173,
-5668331567128.57054,
-681708231403.55141,
6352085891776.81501,
-2750911716113.69637,
-3329430177170.00790,
1128733518605.86589,
-4567800599810.81442,
5368548700520.67049
])

In [184]:
ldif = l1-l0
ndif = np.linalg.norm(ldif)
print(ndif)
ndef = np.linalg.norm(l0)
print(ndef)

3348161359.9039965
44675635885108.74


In [187]:
print(n1)

0.10000000000001424


In [188]:
print(ndif)

3348161359.9039965
